[workspace]
authors = ["Liuchuan Yu <lyu20@gmu.edu>"]
channels = ["conda-forge"]
name = "VR-for-Humanoid-Locomotion"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
pandas = ">=2.0"
pyarrow = ">=14.0"
trimesh = ">=4.11.2,<5"
pillow = ">=12.1.1,<13"
numpy = ">=2.4.2,<3"

[pypi-dependencies]
objaverse = ">=0.1"
